---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 14

inputs:
  - name: dp-table-builder-ui

outputs:
  - name: build
  - name: package

run:
  path: dp-table-builder-ui/ci/scripts/build.sh
