---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 20.19.2

inputs:
  - name: dp-table-builder-ui

outputs:
  - name: build

run:
  path: dp-table-builder-ui/ci/scripts/build.sh
